name: CrossBuild

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:  [ ubuntu-latest ]
        arch: [ i686, riscv64, powerpc, powerpc64, powerpc64le, s390x, sparc64, m68k, sh4, alpha ]
        include:
          - os: ubuntu-24.04-arm
            arch: arm
          - os: ubuntu-24.04-arm
            arch: aarch64
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        submodules: 'recursive'

    - name: Install cross tools
      run: |
        sudo apt-get update
        sudo apt-get install -y sudo qemu-user gdb zstd dwarfdump
        if [[ "${{matrix.arch}}" != "arm" ]]; then
          sudo apt-get install -y {gcc,g++}-14-${{matrix.arch}}-linux-gnu
        else
          sudo apt-get install -y {gcc,g++}-14-arm-linux-gnueabihf
          sudo ln -sf /usr/bin/arm-linux-gnueabihf-gcc-14 /usr/bin/arm-linux-gnu-gcc-14
          sudo ln -sf /usr/bin/arm-linux-gnueabihf-g++-14 /usr/bin/arm-linux-gnu-g++-14
          sudo ln -sf /usr/arm-linux-gnueabihf /usr/arm-linux-gnu
          sudo ln -sf /usr/arm-linux-gnueabihf/lib/ld-linux-armhf.so.3 /lib/ld-linux-armhf.so.3
        fi


    - name: Build
      run: |
        mkdir -p ${{github.workspace}}/build
        cd ${{github.workspace}}/build
        env CXX=/usr/bin/${{matrix.arch}}-linux-gnu-g++-14 CC=/usr/bin/${{matrix.arch}}-linux-gnu-gcc-14 cmake .. -DSPM_BUILD_TEST=ON -DBUILD_SHARED_LIBS=OFF -DSPM_ENABLE_SHARED=OFF -DCMAKE_FIND_ROOT_PATH=/usr/${{matrix.arch}}-linux-gnu -DSPM_CROSS_SYSTEM_PROCESSOR=${{matrix.arch}}
        make -j$(nproc)

    - name: Test on QEMU
      if: matrix.arch != 'sparc64' && matrix.arch != 'm68k' && matrix.arch != 'sh4'
      run: |
        cd ${{github.workspace}}/build
        qemu_arch=`echo ${{matrix.arch}} | sed -e s/powerpc/ppc/ -e s/686/386/`
        qemu-${qemu_arch} -L /usr/${{matrix.arch}}-linux-gnu src/spm_test
      env:
        TEST_SRCDIR: ${{github.workspace}}/data
